In [30]:
import pandas as pd

In [32]:
df = pd.read_csv("datatypes.csv")
df = df.sort_values("id")
z = 'id required description value_type nullable allowed_values'.split()
df = df[z]
df

,id,required,description,value_type,nullable,allowed_values
0,age_group,False,NaN,str,False,misc/age_groups
1,city_district,False,An administrative subdivision of a municipality,str,False,regions/city_districts
2,country,False,"A country, past or present",str,False,regions/nations
3,country_of_birth,False,Subjects country of birth,str,False,NaN
4,county,False,"A Swedish county (län), past or present",str,False,regions/counties
5,crime_code,False,A crime code (brottskod) used by the Swedish p...,str,False,misc/crime_codes
6,crime_type,False,A crime type (brottstyp) used by the Swedish p...,str,False,misc/crime_types
7,date,False,An ISO 8601 date/time stamp,date,False,NaN
8,gender,False,A subjects gender,str,False,misc/gender
9,measure,False,Count or rate for example,str,False,misc/measures
10,month,False,A gregorian month,str,False,periods/months
11,municipality,False,"A Swedish municipality, past or present",str,False,regions/municipalities
12,period,False,A period of time,str,False,periods/*
13,periodicity,False,How long is the period covered by this datapoint,str,False,misc/periodicity
14,quarter,False,A quarter of a gregorian calendar year,str,False,periods/quarters
15,region,False,A Swedish administrative region,str,False,regions/*
16,source_id,False,A key or identifyer used by the data source. P...,str,False,NaN
17,value,False,Value,"int,float",False,NaN
18,year,False,A gregorian year,int,False,NaN

In [33]:
df.to_csv("datatypes.csv",index=False)